config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  root "pages#index"
  get "pages/help"
  
  resources :users
  resources :topics
  get      "/login", to: "sessions#new"
  post     "/login", to: "sessions#create"
  delete  "/logout", to: "sessions#destroy"
  
  get "favorites/index"
  post "favorites", to: "favorites#create"
  delete "favorites", to: "favorites#destroy"
  
  get "comments/new" 
  post "comments", to:"comments#create"
  
  get "information" => "pages#info"
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :image 
  belongs_to :topic
  belongs_to :user
  validates :content, presence:true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates :user_id, presence: true
  validates :topic_id, presence: true
 
  belongs_to :user
  belongs_to :topic
  
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence:true
  
  belongs_to :user
  
  mount_uploader :image, ImageUploader
  
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: "user"
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :password, presence: true, length: { minimum: 8 ,maximum: 32 }, format: /\A(?=.*?[a-z])(?=.*?\d)[a-zA-Z\d]{8,32}+\z/
  # validates :password_confirmation, presence: true, length: { minimum: 8 ,maximum: 32 }, format: /\A(?=.*?[a-z])(?=.*?\d)[a-zA-Z\d]{8,32}+\z/
  
  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: "topic"
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  add_flash_types :success, :info, :warning, :danger
  
  helper_method :current_user, :logged_in?
  
  def current_user
     @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @comment = Comment.new
    @topic = Topic.find(params[:topic_id])
  end
  def create
     @comment = current_user.comments.new(comment_params)
     @comment.topic_id = params[:comment][:topic_id]
     @comment.user_id = current_user.id
    if @comment.save
      flash.now[:success] = "コメントしました"
      redirect_to topics_path
    else
      flash.now[:danger] = "コメントできません"
      render :new
    end 
  end
  
  private
    def comment_params
      params.require(:comment).permit(:content, :topic_id, :user_id)
    end 
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end
  
  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    
    if favorite.save
      redirect_to topics_path, success: "お気に入りに登録しました"
    else
      redirect_to topics_path, danger: "お気に入り登録に失敗しました"
    end
  end
  def destroy
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    favorite = Favorite.find_by(topic_id: params[:topic_id],user_id: current_user.id)
    if favorite.destroy
      redirect_to topics_path, success:"お気に入りを外しました"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
  
  def info
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  def create 
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      log_in user
      redirect_to root_path,success: "ログインに成功しました"
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end
  
  private
  def log_in(user)
    session[:user_id] = user.id
  end
  

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def session_params
    params.require(:session).permit(:email,:password)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :login_check#, only: [:new, :edit, :update, :destroy]
  def index
    @topics = Topic.all.includes(:favorite_users)
  end
  
  def new
    @topic =Topic.new
  end
  
  def create
    @topic = current_user.topics.new(topic_params)
    
    if @topic.save
      redirect_to topics_path, success: "投稿に成功しました"
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end
    
  def login_check
    unless logged_in?
      flash[:alert] = "ログインしてください"
      redirect_to root_path
    end
  end
  
  def show
    @topic = Topic.find_by(id: params[:id])
    @user = @topic.user
    @favorites_count = Favorite.where(topic_id: @topic.id).count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: "登録が完了しました"
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 include SessionsHelper
 
 
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="topic-index-wrapper">
  <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <h1 class="text-center">Comment</h1>
          <%= form_for @comment do |f| %>
            <div class="form-group">
              <%= f.label :content %>
              <%= f.text_area :content, class: "form-control" %>
            </div>
            <%= f.hidden_field :topic_id,value: params[:topic_id] %>
            <% if logged_in? %>
             <%= f.submit "コメントする", class: "btn btn-black btn-block" %>
            <% end %>
          <% end %>
        </div>
      </div>
  </div>
</div>
        
          

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag "logo.png", class: "navbar-brand" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to favorites_index_path do %>
                <%= image_tag "heart.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_topic_path do %>
                <%= image_tag "camera.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOuto(5000);
      });
    </script>
  </body>
</html>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Make you happy</h1>
    <h2 class="text-white">Pictgram is a servise that you can post photos.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to "Sign up", new_user_path, class: "btn btn-block btn-white" %>
      </div>
      <div class="col-md-3">
        <%= link_to "Log in", login_path, class: "btn btn-block btn-white" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/info.html.erb
<section class="legal" id="privacy">
<div class="contentArea">
<h1 class="txtC">個人情報保護方針</h1>
<p>当社は、当社が取り扱う全ての個人情報の保護について、社会的使命を十分に認識し、本人の権利の保護、個人情報に関する法規制等を遵守します。また、以下に示す方針を具現化するための個人情報保護マネジメントシステムを構築し、最新のＩＴ技術の動向、社会的要請の変化、経営環境の変動等を常に認識しながら、その継続的改善に、全社を挙げて取り組むことをここに宣言します。</p>
<h2>１．個人情報保護の基本方針</h2>
<ul class="lv2 mb20">
<li>個人情報は、プログラミング学習サービス業務における当社の正当な事業遂行上及び従業員の雇用、人事管理上必要な範囲に限定して、取得・利用及び提供をし、特定された利用目的の達成に必要な範囲を超えた個人情報の取扱い（目的外利用）を行いません。また、目的外利用を行わないための措置を講じます。</li>
<li>個人情報保護に関する法令、国が定める指針及びその他の規範を遵守いたします。</li>
<li>個人情報の漏えい、滅失、棄損き損などのリスクに対しては、合理的な安全対策を講じて防止すべく事業の実情に合致した経営資源を注入し個人情報セキュリティ体制を継続的に向上させます。また、個人情報保護上、問題があると判断された場合には速やかに是正措置を講じます。</li>
<li>個人情報取扱いに関する苦情及び相談に対しては、迅速かつ誠実に、適切な対応をさせていただきます。</li>
<li>個人情報保護マネジメントシステムは、当社を取り巻く環境の変化を踏まえ、適時・適切に見直してその改善を継続的に推進します。</li>
</ul>
<p class="txtR mb40">
制定年月日 2018年12月28日<br>
最終改正年月日 2019年6月4日<br>
株式会社侍<br>
代表取締役社長 木内 翔大
</p>
<h2>２．当社が取り扱う個人情報の利用目的</h2>
<ul class="lv2">
<li>
ご本人様から直接書面によって取得する個人情報（ホームページや電子メール等によるものを含む）の利用目的<br>
取得に先立ち、ご本人様に対し書面により明示します。
</li>
<li>
前項以外の方法によって取得する個人情報の利用目的
<table>
<thead>
<tr>
<th>分類</th>
<th>利用目的</th>
</tr>
</thead>
<tbody>
<tr>
<td>個人のお客様情報</td>
<td>
ユーザー様サポートのため<br>
ご利用履歴管理のため<br>
当社サービスのご案内のため<br>
お問合せ対応のため
</td>
</tr>
<tr>
<td>お取引先担当者様情報</td>
<td>発注内容確認のため（通信記録等）</td>
</tr>
<tr>
<td>業務の受託に伴い、お客様からお預かりする個人情報</td>
<td>委託された当該業務を適切に遂行するため</td>
</tr>
</tbody>
</table>
</li>
</ul>
<h2>３．保有個人データに関する事項の周知</h2>
<ul class="lv2">
<li>事業者の名称<br>株式会社侍</li>
<li>
個人情報の保護管理者
<table>
<tbody>
<tr><td>管理者名</td><td>橋本 伸也</td></tr>
<tr><td>所属部署</td><td>コンサルティング部</td></tr>
<tr><td>連絡先</td><td>メールアドレス：support@sejuku.net<br>TEL：03-5790-9039</td></tr>
</tbody>
</table>
</li>
<li>
全ての保有個人データの利用目的
<table>
<thead>
<tr><th>分類</th><th>利用目的</th></tr>
</thead>
<tbody>
<tr>
<td>個人のお客様情報</td>
<td>ユーザー様サポートのため<br>ご利用履歴管理のため<br>当社サービスのご案内のため<br>お問合せ対応のため</td>
</tr>
<tr>
<td>お取引先担当者様情報</td>
<td>発注内容確認のため（通信記録等）</td>
</tr>
<tr>
<td>当社従業員情報</td>
<td>社員の人事労務管理、業務管理、健康管理、セキュリティ管理のため</td>
</tr>
<tr>
<td>当社への採用応募者情報</td>
<td>採用応募者への連絡と当社の採用業務管理のため</td>
</tr>
<tr>
<td>人材紹介事業に関する求職者情報</td>
<td>求職者への連絡のため<br>人材紹介業務遂行のため</td>
</tr>
<tr>
<td>特定個人情報</td>
<td>番号法に定められた利用目的のため</td>
</tr>
</tbody>
</table>
</li>
<li>保有個人データの取扱いに関する苦情の申し出先<br>後記５記載のとおり</li>
</ul>
<h2>４．開示等のご請求手続き</h2>
<p class="mb20">当社で保有している保有個人データに関して、ご本人様又はその代理人様からの利用目的の通知、開示、内容の訂正、追加又は削除、利用の停止、消去及び第三者への提供の停止の請求（以下、「開示等の請求」といいます）につきましては、以下の要領にて対応させていただきます。</p>
<ul class="lv2">
 <li>開示等の求めの申し出先<br>開示等のお求めは、後記５記載の当社の個人情報問合せ窓口にお申し出ください。</li>
<li>
開示等の求めに関するお手続き
<ul class="lv1">
<li>お申し出受付け後、当社から、ご利用いただく所定の請求書様式「開示対象個人情報開示等請求書」を郵送いたします。</li>
<li>ご記入いただいた請求書、代理人様によるお求めの場合は代理人であることを確認する書類、手数料分の郵便為替（利用目的の通知並びに開示の請求の場合のみ）を個人情報問合せ窓口までご郵送ください。</li>
<li>上記請求書を受領後、ご本人様確認のため、当社に登録していただいている個人情報のうちご本人の確認が可能な2項目程度（例：電話番号と生年月日等）の情報をお問合せさせていただきます。</li>
<li>回答は原則としてご本人様に対して書面（封書郵送）にておこないます。</li>
</ul>
</li>
<li>
代理人様によるお求めの場合<br>
開示等をお求めになる方が代理人様である場合は、代理人である事を証明する資料及び代理人様ご自身を証明する資料を同封してください。各資料に含まれる本籍地情報は都道府県までとし、それ以降の情報は黒塗り等の処理をしてください。また各資料は個人番号を含まないものをお送りいただくか、全桁を墨塗り等の処理をしてください。
<ul class="lv1">
<li>
代理人である事を証明する資料
<table>
<tbody>
<tr>
<th>開示等の求めをすることにつき本人が委任した代理人様の場合</th>
<td>本人の委任状（原本）</td>
</tr>
<tr>
<th>代理人様が未成年者の法定代理人の場合</th>
<td>戸籍謄本<br>住民票（続柄の記載されたもの）<br>その他法定代理権の確認ができる公的書類<span>※いずれかの写し</span></td>
</tr>
<tr>
<th>代理人様が成年被後見人の法定代理人の場合</th>
<td>後見登記等に関する登記事項証明書<br>その他法定代理権の確認ができる公的書類<span>※いずれかの写し</span></td>
</tr>
</tbody>
</table>
</li>
<li>
代理人様ご自身を証明する資料
<ul class="lvdot">
<li>運転免許証</li>
<li>パスポート</li>
<li>健康保険の被保険者証</li>
<li>住民票</li>
</ul>
</li>
<li>利用目的の通知または開示のお求めについての手数料<br>1回のお求めにつき1000円<br>（お送りいただく請求書等に郵便為替を同封していただきます。）</li>
</ul>
</li>
</ul>
<h2>５．お問い合わせ窓口</h2>
<p class="mb20">
当社の個人情報保護方針に関するお問合せや、個人情報に関する訂正、利用停止、苦情、開示などは、下記窓口にて承っております。
</p><address>
株式会社侍 個人情報問合せ窓口<br>
〒150-0043 東京都渋谷区道玄坂2丁目11-1 Ｇスクエア渋谷道玄坂 4F<br>
<a href="mailto:support@sejuku.net">メールアドレス：support@sejuku.net</a><br>
 <a href="tel:0357909039">TEL：03-5790-9039</a>
</address>
<p></p>
</div>
</section>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <% if !topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                <i class="fa fa-heart favorite-btn"></i>
              <% end %>
            <% else %>
              <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                <i class="fa fa-heart red-favorite-btn"></i>
              <% end %>
            <% end %>
            
              <%= topic.favorites.count %>
            
            <%= link_to comments_new_path(topic_id: topic.id) do %>
              <%= image_tag "comment.png", class: "topic-index-icon" %>
            <% end %>
              
            <p class="topic-text">
              <%= topic.description %>
            </p>
            <% topic.comments.each do |comment| %>
              <p><%= comment.content %></p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 usera-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: "text-white" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: "text-white" %>
            <%= f.text_field :email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: "text-white" %>
            <%= f.password_field :password, class: "form-control" %>
          </div>
          <div class="form-group">
            <%=f.label :password_confirmation, class: "text-white" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>
          
          <%= f.submit "登録", class: "btn-block btn-white" %>
        <% end %>
        <%= link_to "ログインはこちら", login_path, class: "text-white" %>
      </div>
    </div>
  </div>
</div>